### ISSUE TITLE
Display issues with some locales

### ISSUE THREAD

**Issue by yura-pakhuchiy** [zcoinofficial/electrum-xzc#13]
If locale is set to `ru_RU.UTF-8` electrum shows incorrect value in amount column.
Workaround is to start with another locale, eg.:
```
LC_NUMERIC=C electrum-xzc 
```
or
```
LC_ALL=en_US.UTF-8 electrum-xzc 
```

**Comment by coolcow** [comment]
i can confirm this issue.

`~ $ electrum-xzc` => 
![auswahl_013](https://user-images.githubusercontent.com/2337234/46250591-d62b2100-c43d-11e8-8d56-e5ced174176f.png)

`~ $ LC_ALL=C electrum-xzc` =>
![auswahl_014](https://user-images.githubusercontent.com/2337234/46250593-e17e4c80-c43d-11e8-8888-50bb0726b49d.png)

```
~ $ locale -a
C
C.UTF-8
de_AT.utf8
de_BE.utf8
de_CH.utf8
de_DE.utf8
de_IT.utf8
de_LI.utf8
de_LU.utf8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
fr_BE.utf8
fr_CA.utf8
fr_CH.utf8
fr_FR.utf8
fr_LU.utf8
POSIX
```

**Comment by yura-pakhuchiy** [comment]
No longer happens in the latest release.
