### ISSUE TITLE
Ledger Nano S 'NoneType' object has no attribute 'handler'

### ISSUE THREAD

**Issue by MrMonotone** [zcoinofficial/electrum-xzc#15]
While going through the install wizard, when I click next after selecting my hardware device (Ledger Nano S), the following error occurs:

'NoneType' object has no attribute 'handler'

I am using the standalone executable.

**Comment by riordant** [comment]
Hi, we are aware of this issue and taking steps to resolve.

**Comment by riordant** [comment]
Hi, this is fixed as of the latest commit.
I've noticed that sometimes when creating a new wallet, it will show the message "no hardware device detected". This is fixed by quitting the Zcoin app on the Ledger and re-entering into it. It's pretty consistent now.
What OS are you using?

**Comment by riordant** [comment]
Release has been issued with this fix. Closing.

**Comment by MrMonotone** [comment]
@riordant confirming fixed.

**Comment by 2Bsafe76** [comment]
Hello,
I have the same issue. I'm using Electron-Cash-4.0.5- setup and portable. 
Ledger firmware version is 1.5.5
I want to use Electron-Cash to split my Bitcoin Cash and Bitcoin SV.
