### ISSUE TITLE
Same problem like "Ledger Nano S 'NoneType' object has no attribute 'handler' #15"

### ISSUE THREAD

**Issue by sbalza75** [zcoinofficial/electrum-xzc#19]
Hi everybody,
I have the same problem reported in this topic -> https://github.com/zcoinofficial/electrum-xzc/issues/15
First of all I've installed 3.3.1 version and I obtained error message.
Then I've downloaded 3.3.4 version but the problem persist with the same message.
Have you any workaround? Thanks in advance.

PS: my SO is WIN10

**Comment by sbalza75** [comment]
Nobody can help me? Thanks in advance.

**Comment by sbalza75** [comment]
Hi @a-bezrukov, have you good news for me?
Thanks in advance.

**Comment by a-bezrukov** [comment]
Hi @sbalza75 !

Please accept my apologies for not addressing the issue earlier. 
I tried to reproduce and was not able to. So, we need to gather more data on the issue. 
Please initialize your Ledger Live and install Bitcoin, Ethereum and Zcoin apps. Please also upgrade the firmware if your Ledger Live reports it is outdated. 
Please uninstall you previous version of Electrum-XZC and install the latest 3.3.4a1 from the releases tab here: https://github.com/zcoinofficial/electrum-xzc/releases
Please connect your Ledger Nano S to your Windows machine, launch Electrum-XZC and initialize a wallet with a Ledger Nano S connection. 

Which step does the issue appear on?

**Comment by sbalza75** [comment]
Hi @a-bezrukov,
thank you very much for your answer.
I've an error message when click NEXT in the window "Hardware keystore - Select a device - an unnamed ledger [ledger, initialized, hid]". With new version ( I use portable version) I've a different message "Failed to create a client for this device. Make sure it is in the correct state."

Is it a safety step update Ledger Nano's firmware?
Thank you very much.

**Comment by a-bezrukov** [comment]
Hi @sbalza75,
You are welcome!
Is Zcoin application open on your Nano S? Please try to reconnect your Nano S to your USB port, then open the Zcoin application on your Nano S and then launch Electrum-XZC.
Yes, I think it's safe to upgrade with Ledger Live.
Regards,
AB

**Comment by sbalza75** [comment]
Hi @a-bezrukov , I don't have Zcoin application in my Nano S. Is it mandatory? Thanks in advance.

**Comment by a-bezrukov** [comment]
Hi @sbalza75,
NP. Yep, Bitcoin, Ethereum and Zcoin are mandatory.
Regards,
AB

**Comment by sbalza75** [comment]
Hi @a-bezrukov,
I've just upgraded firmware.
I've installed Bitcoin, Bitcoin Cash, Zcash, Ethereum app.
I've installed and open Zcoin Application.
I've launched "Electron-Cash-3.3.4CS-portable.exe" and followed these steps:
1)New/Restore
2) Rename wallet from wallet_1 to hardware_ledger_wallet
3) Standard wallet
4) Use a hardware device
5) Select device: an unnamed ledger [ledger initialized]
ERROR: Exception : Invalid status 6b00
:-((((((((((((((((

**Comment by a-bezrukov** [comment]
Hi @sbalza75,
The only thing that's left is to open the coin app on the Nano S after step 5.
Regards,
AB

**Comment by riordant** [comment]
@sbalza75 Are you launching the Electron-Cash app on Windows, or the electrum-xzc Windows app?

**Comment by sbalza75** [comment]
Hi @riordant,
I launch directly "Electron-Cash-3.3.4CS-portable.exe".
Thanks.

**Comment by a-bezrukov** [comment]
@sbalza75, Can you confirm the issue with Electrum-XZC 3.3.4a2 from here: https://github.com/zcoinofficial/electrum-xzc/releases ?

**Comment by a-bezrukov** [comment]
Closing as it seems that another wallet was in questiong

**Comment by sbalza75** [comment]
Hi, with Electrum-XZC 3.3.4a2 is it ok!!! Thank you very much! Sorry for delay.
