### ISSUE TITLE
Handler missing for Ledger

### ISSUE THREAD

**Issue by NeoButane** [zcoinofficial/electrum-xzc#20]
I had an issue with signing transactions, but not receiving them. The bitcoin Electrum client works fine. I installed the PyPi ledger package locally from source due to package maintenance issues. But when trying to send xzc txs I would get `Handler missing for Ledger'. I think I fixed this from [Monero's guide](https://github.com/LedgerHQ/ledger-app-monero/blob/master/doc/user/bolos-app-monero.rst) below:

> System Configuration
> Linux
> The following packages must be installed: pcsc-tools pcscd libpcsclite1:amd64 .
> You have to have to add the NanoS to /etc/libccid_Info.plist 
> [...]

This was using 1.5.5 Ledger Nano S, 1.4.4 Ledger Live, and the current electrum-xzc package. I'm wondering what this did to fix this so I know how to fix it again in the future.

**Comment by a-bezrukov** [comment]
Hi @NeoButane ,

Generally speaking for Linux systems I need to install the deps and configure my user's permissions. This is covered in these two guides: https://support.ledger.com/hc/en-us/articles/360006395553-Download-and-install-Ledger-Live and https://support.ledger.com/hc/en-us/articles/115005161925-Set-up-and-use-Electrum . 

Please close the issue if it has been resolved,
AB
