### ISSUE TITLE
Electrum + Multisig (Trezor + ColdCard)

### ISSUE THREAD

**Issue by Perlover** [zcoinofficial/electrum-xzc#29]
Electrum 3.3.8 + ColdCard python module (current version) + Trezor python module

I created multisig wallet 2/2. I could choose only "Legacy type" for both hardware wallets.
After creation i got a 3**** bitcoin address and for test i send there $20

After i cannot send from multisig wallet to bech32 / 3*** addresses. The Trezor shows a receiver address and i can approve but ColdCard wallet - nothing happens there. The Electrum shows to me modal error message: "no support yet for inputs of type: p2sh".

**Comment by justanwar** [comment]
Are you sure you got the correct repo? Our releases only goes up to 3.3.6 and we are not Bitcoin.

**Comment by Perlover** [comment]
Sorry, you are right ;-)
