### ISSUE TITLE
Introduce the znode management functionality (pre-DIP3)

### ISSUE THREAD

**Issue by a-bezrukov** [zcoinofficial/electrum-xzc#32]
Electrum-XZC should have the functionality for znode management. 

- [x] Merge the Dash Electrum code for znode management into Electrum-XZC

**Comment by qashban4** [comment]
@a-bezrukov Can you conclude this week

**Comment by a-bezrukov** [comment]
https://github.com/zcoinofficial/electrum-xzc/releases/tag/3.3.8a1
