### ISSUE TITLE
missing modules

### ISSUE THREAD

**Issue by Tcll** [zcoinofficial/electrum-xzc#36]
initial installation startup:
`Error: no module named 'dns'.`
after copying `packages/` from electrum (original wallet):
`ModuleNotFoundError: No module named 'bls_py'`
from module `dash_net.py` line 38

I'm just running a raw python3 installation on the latest Void Linux (32bit)

are there any other dependencies I should include??
python can be pretty annoying at times :P

**Comment by Tcll** [comment]
welp, sorry about this one
I wasn't aware of the required dependencies needed to get this thing working
I was expecting this to be like electrum where you can just download and run...
not sure why bls_py isn't included since that's a 100% python module
but cryptodome can't be included unless it can be spot-compiled at runtime (or has a py3-agnostic binary)

it looks like that's all that's needed though
during the time of this issue I've run across many other electrum-based wallets which seem to require many more binaries.

anyways, closing this as I was oblivious

**Comment by Tcll** [comment]
reopening because I managed to get it working, meaning this issue is valid.
cryptodome was not needed, all that's needed is [bls_py](github.com/zebra-lucky/python-bls/tree/master/bls_py)
just clone as zip and extract the directory to `packages/`

there's a minor error about `bls_py.fields` can't be imported
but you'll get a window regardless :)

+1 for managing to be the closest 3rd-party wallet to Electrum yet ;)
(or should I say the only privacy-coin wallet that doesn't need binaries)

**Comment by a-bezrukov** [comment]
Thanks for pointing to this. Will fix soon.

**Comment by a-bezrukov** [comment]
This tar.gz installation method is not supported anymore and the gzip archive that is on the releases page contains the sources, not the installation. I checked that other installation methods, namely the AppImage and the development installation (`python3 -m pip install .[fast]`) work OK. 
Closing for now, please feel free to reopen it preferably with some steps to reproduce.

**Comment by a-bezrukov** [comment]
I've added a tar.gz including packages to the release. I'll be adding it further. It should have all the modules.

**Comment by Tcll** [comment]
I want to add, I did neither the tgz or gzip methods
in fact I did something I now realize I probably shouldn't've done and just cloned the repo as a zip

lol when you work with python, sometimes your head can get lost in places like this XD
buuuuut I did the same with electrum, and that works, so that's where the focus of this issue was :)

that said though, I probably should've downloaded a **stable** release :P
I accept my fault there

still though, it's good to know everything's included now :)
