### ISSUE TITLE
Not being able to sign message

### ISSUE THREAD

**Issue by jack60612** [zcoinofficial/electrum-xzc#38]
I am using a ledger hardware wallet and whenever i try to sign a message i get an error saying 
"Unicode-objects must be encoded before hashing"

**Comment by justanwar** [comment]
Which Ledger wallet and what operating system are you using?

**Comment by jack60612** [comment]
Ledger nano s and windows 10

**Comment by a-bezrukov** [comment]
Please list the steps to reproduce. It would be very nice to know what kind of message it is and what are the steps taken to create the Electrum-XZC wallet.

**Comment by jack60612** [comment]
I downloaded the wallet from github releases
installed it then i created a wallet using the setup tool with a ledger
nano s as my hardware wallet. then i received zcoin then i tried to test
send a message and it didn't work.
