### ISSUE TITLE
Unable to spend XZC from trezor via Electrum-XZC

### ISSUE THREAD

**Issue by akshaynexus** [zcoinofficial/electrum-xzc#39]
I get the following error while trying to spend xzc from a trezor with the electrum wallet.This is the error:
`ProcessError: Encountered invalid prev_hash`

Traceback:
```
Traceback (most recent call last):
  File "electrum_xzc/gui/qt/util.py", line 718, in run
  File "electrum_xzc/wallet.py", line 1115, in sign_transaction
  File "/var/folders/n9/vwm9k4xs06nbyvcnk9w0znz80000gn/T/_MEIq3fFpY/electrum_xzc/plugins/trezor/trezor.py", line 91, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/var/folders/n9/vwm9k4xs06nbyvcnk9w0znz80000gn/T/_MEIq3fFpY/electrum_xzc/plugins/trezor/trezor.py", line 336, in signtransaction
    signatures,  = client.sign_tx(self.get_coin_name(), inputs, outputs, details=details, prev_txes=prev_tx)
  File "/var/folders/n9/vwm9k4xs06nbyvcnk9w0znz80000gn/T/_MEIq3fFpY/electrum_xzc/plugins/trezor/clientbase.py", line 224, in sign_tx
    return trezorlib.btc.sign_tx(self.client, *args, **kwargs)
  File "/var/folders/n9/vwm9k4xs06nbyvcnk9w0znz80000gn/T/_MEIq3fFpY/electrum_xzc/plugins/trezor/clientbase.py", line 74, in exit
    raise RuntimeError(str(e)) from e
RuntimeError: ProcessError: Encountered invalid prev_hash
```

I have updated trezor to latest firmware version thinking that was the issue,still same error after updating

**Comment by a-bezrukov** [comment]
Hi, @akshaynexus 
Please check if there are Sigma transactions selected as the inputs for the the crashing tx.

**Comment by akshaynexus** [comment]
yes,the inputs are sigma inputs

**Comment by a-bezrukov** [comment]
Please downgrade to the previous release or chose no Sigma spends as the tx outputs. I'll fix it quite soon.

**Comment by akshaynexus** [comment]
Using previous version also fails to spend the coins.I suppose sigma spends is not possible in electrum currently?

**Comment by a-bezrukov** [comment]
Thanks for your input. Yes, it looks like it's not possible to use a Trezor device to sign a tx which input is a Sigma spend at the moment. Using just Electrum-XZC is OK in this case.

**Comment by akshaynexus** [comment]
is it planned to support sigma spends on trezor soon?cant move my funds due this.

**Comment by a-bezrukov** [comment]
Yes, it'll be supported soon but I have just ordered a Trezor device, so ETA is 2-3 weeks. 
There are 2 options to get access to your funds. 
1. Set up an Electrum-XZC wallet without the Trezor, but with entering the BIP39 seed words that the Trezor generated during setup into Electrum-XZC (maybe the BIP44 checkbox should be enabled). Electrum-XZC will generate a wallet with the same private key and all the funds will be accessible.
2. Avoid selecting the Sigma spends in the "Coin" control tab. The View -> Show Coins menu option to activates the tab. Now Sigma spends can be avoided when generating a new transaction.

**Comment by akshaynexus** [comment]
Ok

**Comment by akshaynexus** [comment]
Was there any update to this issue?

**Comment by a-bezrukov** [comment]
I've just started today with it. I'll finish in a couple of days. My apologies for the delay (delivery took ways longer than usual)
