### ISSUE TITLE
Getting an error message when attempting to send

### ISSUE THREAD

**Issue by hakonamatata** [zcoinofficial/electrum-xzc#42]
Don't have much additional info to add, attempt to send using a trezor hardware wallet. 

![image](https://user-images.githubusercontent.com/4003969/87800004-3034ea80-c84e-11ea-98a6-5e0e3eceb0c7.png)

**Comment by a-bezrukov** [comment]
Hi, we are waiting for the new firmware. We can spend such TXs from an Electrum-XZC software BIP-39 wallet, created with the Trezor seed words.

**Comment by a-bezrukov** [comment]
Verified fixed after the new firmware
