### ISSUE TITLE
Could not create or open watch-only wallet with latest Electrum-XZC version

### ISSUE THREAD

**Issue by kkostyan** [zcoinofficial/electrum-xzc#43]
Hi, i have download Electrum-XZC 3.3.8 addition 6 and i'm trying to create watch-only wallet with the "Import Zcoin addresses or private keys" option in Install Wizard, then i entered the address "a4stPFsQPS7fHUFxawtTATTYA91g41bDff" and got the following error message:
```
---------------------------
Error
---------------------------
Cannot create window for wallet:
'NoneType' object has no attribute 'type'
---------------------------
OK   
---------------------------
```

Electrum-XZC 3.3.8 addition 4 working fine.

**Comment by justanwar** [comment]
Confirmed, was able to reproduce with the same address.

**Comment by a-bezrukov** [comment]
Will be fixed in the a7 release
