### ISSUE TITLE
Electrum-XZC 'cannot deserialize transaction' error

### ISSUE THREAD

**Issue by kkostyan** [zcoinofficial/electrum-xzc#44]
Hi.
When i try to import my wallet (using it address or private key) into Electrum XZC, i got the following error message during wallet synchronization:
```
20200806T043748.857555Z |    ERROR | electrum_xzc.interface.[electrumx.zcoin.io:50002] | Exception in wrapper_func: SynchronizerFailure('cannot deserialize transaction a55993253f0bda754dd4a4699643fb56f5c36f85fbfa900e3c7215e5f2e0345a',)
Traceback (most recent call last):
  File "electrum_xzc\synchronizer.py", line 224, in _get_transaction
  File "electrum_xzc\transaction.py", line 728, in deserialize
  File "electrum_xzc\transaction.py", line 591, in deserialize
electrum_xzc.transaction.SerializationError: extra junk at the end
```

So, the wallet balance on https://explorer.zcoin.io/address/a4stPFsQPS7fHUFxawtTATTYA91g41bDff is 7.04885703 ZCOIN and in Electrum-XZC is 0 ZCOIN, and transaction 'a55993253f0bda754dd4a4699643fb56f5c36f85fbfa900e3c7215e5f2e0345a' is missing from transactionHistory.

See program log for additional info:
[electrum_log_20200806T043741Z_7008.log](https://github.com/zcoinofficial/electrum-xzc/files/5032691/electrum_log_20200806T043741Z_7008.log)

**Comment by a-bezrukov** [comment]
![image](https://user-images.githubusercontent.com/36845392/93911098-0519bc00-fd13-11ea-8352-b46ef788e19b.png)
Now it is parsed correctly.
