### ISSUE TITLE
Electrum-XZC showing transactions as unconfirmed when connected to certain servers

### ISSUE THREAD

**Issue by justanwar** [zcoinofficial/electrum-xzc#46]
Electrum-XZC version 3.3.8a6

When connected to electrumx/electrumx03.zcoin.io, several transactions are showing as unconfirmed/unbroadcasted:
Local [rbf, x. sat/b]

However, these transactions are showinng as confirmed when connected to electrumx 01-02.

The transactions in question have more than 40k confirmations on the blockchain.

List of transaction:
```
96a2450117123d9a901e6362ddf0072aa572fa727c609c24c9d87038d3448265
3457b21c01ea92bf155bfa855fbaccc0871342d4a13fdbf69b0d42ca4b4a63e3
46dae844f684fd5ea1a6cc6ed19ad43e000587b3138a521fcd29b6f5889bae7f
```
![image](https://user-images.githubusercontent.com/42809091/91414290-eabd0180-e87e-11ea-828d-14d021c13bbb.png)

**Comment by r1979** [comment]
When connecting to public elecrum-xzc servers I noticed the same, so I tried to set up my own `electrumx` server to test it and in the log of `electrumx` I also see this output:

```
electrumx.server.block_processor.ChainError: UTXO 95319085ed541bf2f6611b6dde362b155557dfc226f3374061850e6
b3ac4a7b4 / 16 not found in "h" table at height 293430
```
I noticed that "local" transactions in my elecrum-xzc wallet start after that block (I see this when I connect to the other public electrum servers).

**Comment by r1979** [comment]
Update: I reindexed my zcoin node with `-reindex` and retried to sync the electrumx server but I get [the same error](https://github.com/zcoinofficial/electrum-xzc/issues/46#issuecomment-690879258).

**Comment by olson777** [comment]
Hi,
Did you manage to solve this problem? I had the same problem, after updating electrum-xzc to version 3.3.8a7 and restoring my wallet, all withdrawal transactions disappeared. These were previously marked as "local" transactions in the old wallet. When I try to withdraw funds, I get the error "The server returned an error while sending a transaction... Missing inputs".

**Comment by justanwar** [comment]
Fixed.

**Comment by r1979** [comment]
@justanwar simply out of curiosity, what was the fix?
