### ISSUE TITLE
Wallet balance on testnet always zero

### ISSUE THREAD

**Issue by yzhang1994** [zcoinofficial/electrum-xzc#47]
Hello,

I acquired some test tokens from the Sigma faucet.

From the sigma explorer, I have 2 Zcoins in my balance: https://testexplorer.zcoin.io/address/TMLtcnx77pcq22MdaRe6K6V4H77sqAuf5x

However, when I run the [quickstart](https://github.com/zcoinofficial/electrum-xzc/blob/master/electrum/scripts/quick_start.py) script (with my local testnet wallet):
The result I get is
`balance {'confirmed': '0'}`

When I run the same script with a main net wallet, the script reads the balance correctly

What am I doing wrong? Is Sigma the correct testnet?

**Comment by a-bezrukov** [comment]
Hi, please add the following server to the testnet server list: 95.179.164.13

**Comment by yzhang1994** [comment]
@a-bezrukov Tried it. Applied the same change in this: https://github.com/zcoinofficial/electrum-xzc/commit/9e5637f8e52d4572836f1afadb46f81fc133e5a1

The balance is still zero.

Also, is there a way to open a testnet wallet in the GUI client?

**Comment by yzhang1994** [comment]
Does the wallet need to be synced somehow?

My mainnet balance is wrong as well, until I open the wallet in the GUI client
