### ISSUE TITLE
withdrawal error

### ISSUE THREAD

**Issue by olson777** [zcoinofficial/electrum-xzc#48]
electrum-xzc 3,3,8 a7 I'm trying to transfer funds from the wallet, but I get the error "The server returned an error while sending a transaction ...Missing inputs". How to solve this problem?
![2020-09-14_14-09-57](https://user-images.githubusercontent.com/71266042/93086091-40771380-f69f-11ea-959f-a91707f8e6e9.jpg)

**Comment by a-bezrukov** [comment]
Hi, 
Please take the following steps:
1. **The most important** - please backup you wallets' secrets. 
2. Delete your electrum-xzc datadir. 
3. Restore your wallet from the backup that have been made on step 1 and allow the wallet to sync.
There should be no missing inputs error after the wallet synchronizes.

**Comment by olson777** [comment]
Hi,
I did as you said, the servers are synchronized, but the balance is
also wrong. No withdrawal transactions. And when trying to output the
same error appears.
Maybe I have the wrong servers?



2020-09-14 21:15 GMT+03:00, a-bezrukov <notifications@github.com>:

**Comment by a-bezrukov** [comment]
I confirm there is an issue with receiving of spend txs. It'll require time to be fixed.
For now please open the Coin tab and spend only the coins which are marked "unspent" in the explorer.zcoin.io

**Comment by olson777** [comment]
I am trying to withdraw funds, but the same error still occurs - Missing inputs.

2020-09-15 15:17 GMT+03:00, a-bezrukov <notifications@github.com>:

**Comment by a-bezrukov** [comment]
Missing inputs errors happens when a spent input is selected. There are 2 options here: 
1. Check every selected input on the Coins tab of your Electrum-XZC wallet
2. Create a new zcoin-qt wallet using the same seed phrase as your Electrum-XZC wallet

**Comment by olson777** [comment]
The amount of incoming coins is all available, but there are no spent
coins in the wallet, which I previously withdrawn without problems.
Now on the updated wallet the amount is 3.3, but it should be 1.97.
And when trying to withdraw funds, it gives the same error -
"The server returned an error while sending the transaction. Try
connecting to a different server or updating Electrum. Missing
inputs".

2020-09-15 20:49 GMT+03:00, a-bezrukov <notifications@github.com>:

**Comment by olson777** [comment]
"Check every selected input on the Coins tab of your Electrum-XZC wallet"
How to do it practically? Tell us in more detail.

**Comment by a-bezrukov** [comment]
Here you go. 
As I already mentioned above, please open your Electrum-XZC Coins tab (click View->Show Coins if you don't see the tab). On the Coins tab select only the coins that marked as unspent (U) in the insight.zcoin.io block explorer. To do this, please copy the coin address, paste it in the insight.zcoin.io to see if its final value is marked with (U) sign. If it is, please mark this coin somehow for yourself. After all coins have been dealt with, please select only the unspent coins in the Coins tab, right click on the selection and chose the Spend option. 
Please let me know if you need it more detailed breakdown.

**Comment by a-bezrukov** [comment]
It was fixed now. Please backup your wallet seed phrase and resync your wallet.

**Comment by olson777** [comment]
Yes, everything works now. Fine.
