### ISSUE TITLE
Electrum wallet

### ISSUE THREAD

**Issue by XZC12345** [zcoinofficial/electrum-xzc#49]
![Zrzut ekranu 2020-09-25 o 21 41 14](https://user-images.githubusercontent.com/71902233/94309133-e405d500-ff77-11ea-93f1-d8cc8169f180.png)
I have eletrum zcoin 3.3.8 version
The wallet does not connect to servers. Neither automatically or manually.

**Comment by justanwar** [comment]
The servers are back up. Please try again.
