### ISSUE TITLE
electrum-xzc-3.3.8a7-portable

### ISSUE THREAD

**Issue by oxzhor** [zcoinofficial/electrum-xzc#50]
I cannot send coins because i cannot confirm my transaction at my nano s.
![confirm](https://user-images.githubusercontent.com/19476081/99242619-c6c6e780-27ff-11eb-9e60-f7f84c410583.png) how can i fix this issue?

**Comment by justanwar** [comment]
Are these mining inputs? If yes, please try the steps here https://github.com/firoorg/electrum-xzc/issues/28#issuecomment-513573689

**Comment by oxzhor** [comment]
> Are these mining inputs? If yes, please try the steps here [#28 (comment)](https://github.com/firoorg/electrum-xzc/issues/28#issuecomment-513573689)

That also not work. I also get an error in the begin at the nano s ( The derivation path is unusable )  Derivation path (1/8) if i click further then X Reject if you're not sure or Approve derivation path. If i choose Approve derivation path then i see my xzc address in the screen and can Approve.

**Comment by justanwar** [comment]
You need to click approve on the 'the derivation path is unusable' messages, otherwise it will not work.

[https://support.ledger.com/hc/en-us/articles/360015739499](https://support.ledger.com/hc/en-us/articles/360015739499)

**Comment by oxzhor** [comment]
> You need to click approve on the 'the derivation path is unusable' messages, otherwise it will not work.
> 
> https://support.ledger.com/hc/en-us/articles/360015739499

Yes for sure i did that but still i am not able to send my coins because i not get an message to confirm it at my nano s?

**Comment by oxzhor** [comment]
I contact ledger and all is ok, their advice me to contact you guys.

I'm upgrade to electrum-xzc-3.3.8a9-portable and still facing the same problem i cannot confirm at mu ledger because nothing popup.

Please help me to solved this issue.

**Comment by justanwar** [comment]
What is the version of Zcoin app on your ledger? How many inputs does this transaction have?

**Comment by oxzhor** [comment]
> What is the version of Zcoin app on your ledger? How many inputs does this transaction have?

Thank you for your reply.
I run Zcoin 1.5.1 and try to send an low amount but all the time the same result.

**Comment by justanwar** [comment]
![image](https://user-images.githubusercontent.com/42809091/61594743-e2c57380-ac21-11e9-9aa0-b3733e8be333.png)

In Electrum-xzc, select View -> Show coins. Right-click on only one entry and select Spend, then try sending this one out. Your Ledger should prompt you almost immediately.

If that is successful, try Ctrl+Left Click in the Coins tab to select a maximum of five entries. Then right-click and select Spend. You will now notice a bit of sluggishness while waiting for the Ledger to show the transaction approval prompt. 

You can try with 10, 15 or 20 entries at once, but I would not recommend going past 20 since the Ledger will time out.

**Comment by oxzhor** [comment]
Jup i try that to same issue :S

**Comment by justanwar** [comment]
Which operating system, what version? How much are you sending? Are you able to get the Ledger to prompt you when you use Tools -> Sign/Verify Message?

**Comment by oxzhor** [comment]
Hi,

My system windows 10 fully updated. electrum-xzc-3.3.8a9-portable. I try to send one coin two three four five but no succes. I get the Sign/Verify Message screen:

![veri](https://user-images.githubusercontent.com/19476081/101174866-b5c20700-3644-11eb-9a23-6960572f7ea5.png)

**Comment by justanwar** [comment]
At the `Sign/Verify message` window, try pasting an address from your Ledger, type in anything in the `Message` box and click on Sign. Does the Ledger prompt you for with a confirmation?

If the above works, try sending a very small amount (about 0.1 XZC).

**Comment by oxzhor** [comment]
Yes that works.

![sign](https://user-images.githubusercontent.com/19476081/101614404-300bd600-3a0d-11eb-9fc8-b685953f8323.png)
![sign2](https://user-images.githubusercontent.com/19476081/101614416-3306c680-3a0d-11eb-9f04-45bbd1db988f.png)
![sign3](https://user-images.githubusercontent.com/19476081/101614423-3601b700-3a0d-11eb-8941-00b184ec2fc7.png)

**Comment by oxzhor** [comment]
Did you have any solution for me?

**Comment by a-bezrukov** [comment]
Hi @oxzhor , the solution here is to select just a few inputs to be spent. Please refer to this image https://user-images.githubusercontent.com/42809091/61594743-e2c57380-ac21-11e9-9aa0-b3733e8be333.png 
and select just 2 UTXOs to be spent and try spending it. If successful, double the UTXO number and try spending 4. If successful, try spending 8, etc. Eventually, you'll end up with the number of UTXOs that your hardware can handle.

**Comment by oxzhor** [comment]
sadly that is not working like i said before :S

**Comment by a-bezrukov** [comment]
What is the error message?

**Comment by oxzhor** [comment]
I cannot confirm the transaction on my ledger.

**Comment by a-bezrukov** [comment]
Why you cannot? Please provide more details so that we can help you.
For now please ignore the "derivation path is unusual" message and approve the tx.

**Comment by oxzhor** [comment]
> ![image](https://user-images.githubusercontent.com/42809091/61594743-e2c57380-ac21-11e9-9aa0-b3733e8be333.png)
> 
> In Electrum-xzc, select View -> Show coins. Right-click on only one entry and select Spend, then try sending this one out. Your Ledger should prompt you almost immediately.
> 
> If that is successful, try Ctrl+Left Click in the Coins tab to select a maximum of five entries. Then right-click and select Spend. You will now notice a bit of sluggishness while waiting for the Ledger to show the transaction approval prompt.
> 
> You can try with 10, 15 or 20 entries at once, but I would not recommend going past 20 since the Ledger will time out.

I did this with 5 transactions for testing then i get an popup with https://user-images.githubusercontent.com/19476081/99242619-c6c6e780-27ff-11eb-9e60-f7f84c410583.png and no confirm screen on my ledger so i cannot confirm the transaction.

**Comment by a-bezrukov** [comment]
Please strictly follow these steps:
1. Open the Coins tab (No Coins tab? Click View->Show coins)
2. Select 2 UTXOs, try spending just 2 UTXOs

Will it spend successfully?

**Comment by oxzhor** [comment]
Thank you for your reply.

Still same no confirm screen at my ledger

![3](https://user-images.githubusercontent.com/19476081/102604115-fed58900-4123-11eb-968f-9c3a85e9617c.jpg)

**Comment by a-bezrukov** [comment]
Thanks for providing the images, you were doing it as suggested and it should have worked. For now I can only think of some hardware issue, or, maybe, there is some other application which interacts with you Ledger simultaneously.

The incoming transactions sizes are huge, and the limited Ledger capabilities may be not enough for such TXs.

So, if electrum-xzc times out waiting for the confirmation, we can exclude your Ledger device from the workflow. To do so, please recreate your wallet with your seed words, as described here: https://github.com/firoorg/electrum-xzc/issues/21#issuecomment-472604529

**Comment by oxzhor** [comment]
This go to slow, is their an way to speed it up? An couple of UTXOs per time take ages to send them all.

**Comment by a-bezrukov** [comment]
Unfortunately, it's the Ledger hardware limitation. The only way is to recreate a wallet without the device. If recreated without Ledger, more than 2 inputs can be spent.

**Comment by oxzhor** [comment]
Thx i will do that because this take me ages :P

**Comment by oxzhor** [comment]
Credits to https://github.com/firoorg/electrum-firo/issues/21#issuecomment-472604529 perfect i send them all quickly. Topic can be closed.
