### ISSUE TITLE
.dmg file is corrupt for OS Big Sur

### ISSUE THREAD

**Issue by NateNohling** [zcoinofficial/electrum-xzc#54]
3.3.8a9.dmg keeps getting the "Electrum-XZC" is damaged and cant be opened.

**Comment by a-bezrukov** [comment]
I cannot reproduce it. Please check you system security settings which should be the reason for this.

**Comment by NateNohling** [comment]
Heres what I'm getting, just re-downloaded from github. MacOS BigSur 11.1

<img width="236" alt="Screen Shot 2021-01-26 at 2 00 51 PM" src="https://user-images.githubusercontent.com/16629628/105898455-10d9ff80-5fdf-11eb-9de7-5648e2010c4c.png">
<img width="367" alt="Screen Shot 2021-01-26 at 2 01 27 PM" src="https://user-images.githubusercontent.com/16629628/105898465-133c5980-5fdf-11eb-940c-28c29dbc3f27.png">

**Comment by a-bezrukov** [comment]
Yes, we don't have signatures on the image. Please try 
1. Preferred: running the `xattr -cr /path/to/electrum-3.3.8a9.dmg` in a terminal
2. Less secure: lower the whole system security level as described here: https://secure.clcbio.com/helpspot/index.php?pg=kb.page&id=323 or https://apple.stackexchange.com/questions/175634/all-downloaded-files-cannot-be-opened-as-they-are-damaged-and-should-be-moved-t
Don't forget to restore the setting after installing the app
