### ISSUE TITLE
Electrum-XZC 3.8.8 Servers Offline I Need Help

### ISSUE THREAD

**Issue by diemcizone** [zcoinofficial/electrum-xzc#57]
I installed the XZC App along with my Ledger wallet and ran it with the Electrum-XZC 3.8.8 wallet.
Servers are offline and not working, I have tried backup servers and the result has not changed.
I cannot view or withdraw my balance.

**Comment by a-bezrukov** [comment]
All servers are up. Try recreating your electrum-xzc profile dir (renaming it to something like electrum-xzc_backup is a good idea). If it does not help, please create an issue according to the issue template, providing -vdebug output.
