### ISSUE TITLE
File "Electrum_xzc\gui\qt\history_list.py", line 133, in data AssertionError

### ISSUE THREAD

**Issue by firotothemoon** [zcoinofficial/electrum-xzc#59]
### Actual behavior

When I installed the Electrum wallet (Standard type), this error appear and I also restored the wallet from the Firo Core using seeds to the Electrum wallet but the balance was still in the Firo Core and did not appear on the Electrum wallet?

I installed it on Windows 10-10.0.19041-SP0, Electrum version 3.3.8 so I don't know where to run the debug logs?
### Steps to reproduce

1. 
2.
3.

**Comment by justanwar** [comment]
Solved on Discord. Please make sure that `Extend this seed with custom words` is checked when importing seed phrase from Firo QT that contains a 25th word.
